# Site settings
title: Gaussian Process Approximations Workshop, 2017
email:
description: > # this means to ignore newlines until "baseurl:"
  Workshop on Gaussian Process Approximations in Berlin, Germany.
baseurl: "/gpa17" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  gpschool
facebook_page: odsi.sheffield


youtube:
  height: 315
  width: 560

github:
  edit: true
  repository: gpa17

markdown: kramdown

# Build settings
future: true

permalink: "/:categories/:title.html"
banner:

analytics:
 google:
   tracking_id: UA-62991754-1

youtube:
  height: 315
  width: 560

conference:
  draft: true
  hide_tentative: true
  hosts:

  room:
  venue: Amazon Development Center Berlin
  location: Krausenstraße 38, 10117 Berlin, Germany, Berlin, Germany
  name: Gaussian Process Approximations
  year: 2017
  month: May
  dates:
  - 2017-05-29
  - 2017-05-30
  draft: true # set to True if the programme is draft only.
  organizers:
  - name: Cedric Archambeau
     url: "http://www0.cs.ucl.ac.uk/staff/c.archambeau/"
     institute: Amazon
  - name: Pablo Moreno
     url: "https://www.linkedin.com/in/pablo-garc%C3%ADa-moreno-4b812087"
     institute: Amazon
  - name: Neil Lawrence
     url: "http://inverseprobability.com"
     institute: Amazon and University of Sheffield
  - name: Manfred Opper
     url: "http://www.ki.tu-berlin.de/menue/team/manfred_opper/forschungsgebiete/"
     institute: TU Berlin
previous_meeting:
  name: Gaussian Process Approximations, 2015
  url: "http://gpss.cc/gpa15"

map:
  show: False
  mapbox:
    latitude: # latitude of map center
    longitude: # longitude of map center
    map_id: # mapbox id
    access_token: # mapbox access token
    zoom_level: 17
    width: 100%
    height: 500px

registration:
  fees:
    academy: 
    industry:
    included: 
  deadline: 2017-04-28
  form: https://goo.gl/forms/zgqB7lFUWxckPTrW2
